// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PromptPlayground.Services;

#nullable disable

namespace PromptPlayground.Migrations
{
    [DbContext(typeof(DbStore))]
    partial class DbStoreModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("PromptPlayground.Services.Models.GenerationResultStore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Elapsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GenerationResultStores");
                });

            modelBuilder.Entity("PromptPlayground.Services.Models.GenerationResultStore", b =>
                {
                    b.OwnsOne("PromptPlayground.Services.ResultTokenUsage", "Usage", b1 =>
                        {
                            b1.Property<long>("GenerationResultStoreId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Completion")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Prompt")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Total")
                                .HasColumnType("INTEGER");

                            b1.HasKey("GenerationResultStoreId");

                            b1.ToTable("GenerationResultStores");

                            b1.ToJson("Usage");

                            b1.WithOwner()
                                .HasForeignKey("GenerationResultStoreId");
                        });

                    b.Navigation("Usage");
                });
#pragma warning restore 612, 618
        }
    }
}
